### PR TITLE
Add explanation for Nginx and Supervisor

### PR DESCRIPTION
**Pull request by mattiasgeniar**
Unclear if this would render OK, didn't find a way to generate the HTML yet :-)

### CODE REVIEW

**Comment by acacha** [comment]
@mattiasgeniar @mpociot Are you sure the proposed config is Ok? If I use you proposed configuration in Laravel Forge give me a 502 error gateway no matter what I put in proxy_pass. Also line     proxy_set_header Host $host; is repeated two times...

**Comment by mattiasgeniar** [comment]
> If I use you proposed configuration in Laravel Forge give me a 502 error gateway no matter what I put in proxy_pass. 

Is your websocket server running OK? What happens when you run `curl http://127.0.0.1:6001`? 

Did you modify the paths to the `ssl_certificate` and `ssl_certificate_key`? 

> Also line proxy_set_header Host $host; is repeated two times...

That's a bit mess indeed, I'll clean that up.

**Comment by acacha** [comment]
> Is your websocket server running OK? What happens when you run `curl http://127.0.0.1:6001`?

At least any error is thrown when I executed:

$ /usr/bin/php /home/forge/scool.cat/artisan websockets:serve --verbose
Starting the WebSocket server on port 6001...

The port is open:

```
$ sudo nmap localhost -p 6001

Starting Nmap 7.60 ( https://nmap.org ) at 2018-12-13 09:43 UTC
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000098s latency).
rDNS record for 127.0.0.1: scool-cat.localdomain

PORT     STATE SERVICE
6001/tcp open  X11:1

Nmap done: 1 IP address (1 host up) scanned in 0.26 seconds
```
But no response when running:

```
forge@scool-cat:~$ curl http://127.0.0.1:6001
```

> Did you modify the paths to the `ssl_certificate` and `ssl_certificate_key`?

Yes: 

```
sudo cat /etc/nginx/sites-enabled/00_socket.scool.cat 
server {
  listen        443 ssl;
  listen        [::]:443 ssl;

  server_name   socket.scool.cat;

  # Start the SSL configurations
  ssl                  on;
  ssl_certificate      /etc/nginx/ssl/scool.cat/412609/server.crt;
  ssl_certificate_key  /etc/nginx/ssl/scool.cat/412609/server.key;

  location / {
    proxy_pass             https://127.0.0.1:6001;
    proxy_set_header Host  $host;
    proxy_read_timeout     60;
    proxy_connect_timeout  60;
    proxy_redirect         off;

    # Allow the use of websockets
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }
```

**Comment by acacha** [comment]
I'm not sure I undertand the comment:

```
You can now talk HTTPS to socket.yourapp.tld. You would configure your config/broadcasting.php like the example above, treating your socket server as an https endpoint.
```

Could be someone be more explicit and show a working **config/broadcasting.php** configuration file?

I use:

```
// VERIFY HOST IN PRODUCTION!
        'pusher_production' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'http',
            ],
        ],
```

But I'm not sure it's ok.

**Comment by acacha** [comment]
Sorry 504 Gateway error resolved:

Changed in /etc/nginx/sites-available/00_socket.scool.cat:

```
  location / {
    proxy_pass             https://127.0.0.1:6001;
....
```

to http://127.0.0.1:6001; (without s)

**Comment by acacha** [comment]
Thanks all folks! Working finally I have a full working solution using laravel-wesockets pacakge with Laravel Valet in local and Laravel Forge on server with SSL on both.

As promised my solution explained: with all configuration files explicitly explained:

Proxy configuration at Laravel Forge:

https://github.com/acacha/scool/tree/master/nginx

In my case:

/etc/nginx/ssl/scool.cat/412609

Ara Laravel Forge Let's encrypt certificates (generated using Laravel Forge) for the main site scool.cat. Is a multitenant app so I use a wildcard configuration *. scool.cat (SSL certificate is multidomain).

Very important (at least It was for me my main error) to understant that if we use Proxy nginx the security is added ONLY by nginx so our laravel web sockets daemon running at 6001 will be simple without SSL.

So my Laravel web sockets an Laravel Broadcasting related files are:

https://github.com/acacha/scool/blob/master/config/broadcasting.php

My configuration is a little more complicated because I've using tenants then I have 4 possible pusher connections:

For my main app (no tenant -> scool.cat)
- pusher: Configuration for Laravel Valet on local
- pusher_production: Configuration for Laravel Valet on production
-  For  tenants (*.scool.cat p.ex. tenant1.scool.cat)
- pushe_tenant: Configuration for Laravel Valet on local
- pusher_tenant_production: Configuration for Laravel Valet on production

The most important think as noted is how I use a simple laravel web sockets server without SSL in production.

Web sockets configuration (https://github.com/acacha/scool/blob/master/config/websockets.php):

- I use a custom Apps provider: https://github.com/acacha/scool/blob/master/app/LaravelWebSockets/ConfigAppProvider.php
- It adds an app for main app and one app for every tenant depending on tenant table in database
- SSL is configured using .env variables to use SSL on local with Laravel Valet but not in production

And finally Laravel Echo configuration on client side javascript:

https://github.com/acacha/scool/blob/master/resources/tenant_js/bootstrap.js

I used similar tactics than Laravel with csrf-token so I can use Laravel env info in Javascript because I want different Larave echo object in production and local:

```
if (window.tenant) {
  if (window.tenant.pusher_app_key) {
    if (window.env) {
      if (window.env.app_env) {
        if (window.env.app_env === 'local') {
          window.Echo = new Echo({
            broadcaster: 'pusher',
            key: window.tenant.pusher_app_key,
            wsHost: window.location.hostname,
            wsPort: process.env.MIX_PUSHER_PORT,
            wssPort: 6001,
            disableStats: true,
            encrypted: false
          })
        }
        if (window.env.app_env === 'production') {
          window.Echo = new Echo({
            broadcaster: 'pusher',
            key: window.tenant.pusher_app_key,
            wsHost: 'socket.scool.cat',
            disablestats: true,
            encrypted: true
          })
        }
      }
    }
  }
```
 

A lot of configuration depends on .env files so I put here relevant information:

.env local:

```
WEBSOCKETS_LOCAL_CERT=/home/sergi/.valet/Certificates/scool.test.crt
WEBSOCKETS_LOCAL_PK=/home/sergi/.valet/Certificates/scool.test.key
WEBSOCKETS_VERIFY_PEER=false
```
.env production:
```
WEBSOCKETS_LOCAL_CERT=
WEBSOCKETS_LOCAL_PK=
WEBSOCKETS_VERIFY_PEER=false
```

Also you could see full project code at:

https://github.com/acacha/scool

**Pull request merged**
